---
grails:
    profile: web
    codegen:
        defaultPackage: openthesaurus
---
grails:
    mail:
        host: "smtp.gmail.com"
        port: 465
        username: ""
        password: ""
        props:
            mail.smtp.auth: "true"
            mail.smtp.socketFactory.port: "465"
            mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
            mail.smtp.socketFactory.fallback: "false"
---
grails:
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
        default:
            mapping:
                autowire: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: text
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    flush:
        mode: AUTO
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
#    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    hibernate.dialect: xxx
    hibernateDialect: xxx 
    username: openthesaurus
    password: ******
    properties:
        driverClassName: com.mysql.jdbc.Driver
        maxActive: 80 # default 100
        minIdle: 5 # default initialSize
        maxIdle: 25 # default initialSize
        maxWait: 5000 # default 30000 (30 seconds)
        maxAge: 600000 # default 0
        timeBetweenEvictionRunsMillis: 5000 # default 5000 (5 seconds)
        minEvictableIdleTimeMillis: 60000 # default maxActive:100
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true # default false
        testWhileIdle: true # default ?
        testOnReturn: false # default false
        jdbcInterceptors: ConnectionState # default null
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:mysql://127.0.0.1:3306/openthesaurus
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://127.0.0.1:3306/openthesaurus
    production:
        dataSource:
#            dbCreate: none # for live production
            dbCreate: create # for new production
            url: jdbc:mysql://127.0.0.1:3306/openthesaurus?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
            properties:
                jmxEnabled: true
                initialSize: 5 # default 10

